/* OLEN 5.0 · CHAT
   Consolidated Chat owner prepared from the current 5/5 behaviour.
   IMPORTANT: intentionally NOT loaded by index.html or sw.js yet.
   Existing conversation data remains owned by the current conversation engine.
*/
(()=>{
'use strict';
const core=window.OLEN?.core;
if(!core||window.OLEN?.chat?.version==='5.0.0')return;
const VERSION='5.0.0',META_KEY='alpha_olen_conversation_meta_v4330';
const OPEN='olenChatOpen500',FS='olenChatFs500',STYLE_ID='olenChat500Style';
const svg=d=>`<svg viewBox="0 0 24 24" aria-hidden="true">${d}</svg>`;
const ICON={compose:svg('<path d="M5.5 3.5H4.75A2.75 2.75 0 0 0 2 6.25v13A2.75 2.75 0 0 0 4.75 22h13A2.75 2.75 0 0 0 20.5 19.25V18"/><path d="M8 16l1.2-4.4 8.45-8.45a2.15 2.15 0 0 1 3.05 3.05l-8.45 8.45L8 16Z"/>'),dots:svg('<circle cx="12" cy="5" r="1.7"/><circle cx="12" cy="12" r="1.7"/><circle cx="12" cy="19" r="1.7"/>'),search:svg('<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.2 4.2"/>'),back:svg('<path d="m15 18-6-6 6-6"/>'),chat:svg('<path d="M21 11.5a8.5 8.5 0 0 1-9 8.4A9.8 9.8 0 0 1 7 18.5L3 20l1.5-4A8.5 8.5 0 1 1 21 11.5Z"/>'),pin:svg('<path d="m9 3 6 6-2 2 3 4-1 1-4-3-2 2-6-6 6-6Z"/><path d="m8 16-5 5"/>'),trash:svg('<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13"/>')};
function conversations(){return core.safe(()=>window.alphaConversations?.()||[],[])}
function current(){return core.safe(()=>window.alphaCurrentConversation?.(),null)}
function meta(){return core.storage().jsonGet(META_KEY,{})||{}}
function saveMeta(value){core.storage().jsonSet(META_KEY,value)}
function key(c){return String(c?.title||'').trim().slice(0,160)}
function label(c,m=meta()){return m[key(c)]?.name||c?.title||'Conversa'}
function activeConversations(){const m=meta();return conversations().filter(c=>!m[key(c)]?.deleted&&!m[key(c)]?.archived)}
function sidebar(){return core.qs('#aiChatMenu')||core.qs('.alphaConversationSidebar')}
function isOpen(){return core.isChat()&&document.body.classList.contains(OPEN)}
function installStyle(){if(core.byId(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
body.${FS}.alphaChatMode #lifestyleAI,body.${FS}.alphaComposeMode #lifestyleAI{position:relative!important}
body.${FS} .olenChatCapsule500{position:absolute;top:calc(env(safe-area-inset-top) + 10px);right:12px;z-index:12010;width:126px;height:48px;border:1px solid #315149;border-radius:999px;background:#10231f;display:flex;overflow:hidden;box-shadow:0 8px 24px rgba(0,0,0,.24)}
body.${FS} .olenChatCapsule500 button{width:63px;height:48px;border:0;background:transparent;color:#eff7f3;display:grid;place-items:center}body.${FS} .olenChatCapsule500 button:active{background:#17372f}body.${FS} .olenChatCapsule500 svg{width:27px;height:27px}
body.${OPEN} .olenChatCapsule500,body.${OPEN} #lifestyleAI .aiChatMenuBtn{visibility:hidden!important;opacity:0!important;pointer-events:none!important}
.olenChatSearch500{position:fixed;inset:0;z-index:2147483020;background:linear-gradient(180deg,#071116,#0b1c22);color:#eff7f3;padding:calc(env(safe-area-inset-top) + 14px) 16px max(14px,env(safe-area-inset-bottom));display:flex;flex-direction:column;font-family:system-ui,-apple-system,sans-serif}.olenChatSearch500 header{display:flex;gap:10px}.olenChatSearch500 button{width:44px;height:44px;border:1px solid #315149;border-radius:50%;background:#10231f;color:#eff7f3}.olenChatSearch500 input{height:48px;flex:1;border:1px solid #29434b;border-radius:24px;background:#0d1a21;color:#eff7f3;padding:0 17px;font-size:16px}.olenChatResults500{overflow:auto;display:grid;gap:8px;padding-top:16px}.olenChatResult500{border:1px solid #294149;border-radius:15px;background:#0d1a21;color:#eff7f3;text-align:left;padding:13px}.olenChatResult500 b{display:block;margin-bottom:4px}.olenChatResult500 span{color:#a9beb7;font-size:14px}
.olenChatActions500{position:fixed;z-index:2147483011;min-width:230px;padding:8px;border:1px solid #294149;border-radius:20px;background:#0b1c22;box-shadow:0 18px 50px rgba(0,0,0,.42)}.olenChatActions500 button{width:100%;height:50px;border:0;border-radius:12px;background:transparent;color:#eff7f3;text-align:left;padding:0 14px}.olenChatActions500 button:active{background:#17372f}.olenChatActions500 .danger{color:#ff858c}
`;document.head.appendChild(s)}
function ensureCapsule(){if(!core.isChat())return;document.body.classList.add(FS);const host=core.byId('lifestyleAI');if(!host||host.querySelector('.olenChatCapsule500'))return;const cap=document.createElement('div');cap.className='olenChatCapsule500';cap.innerHTML=`<button data-chat-action="new" aria-label="Nova conversa">${ICON.compose}</button><button data-chat-action="more" aria-label="Mais opções">${ICON.dots}</button>`;host.append(cap)}
function startFresh(){closeFloating();if(typeof window.alphaStartFreshConversation==='function')return window.alphaStartFreshConversation({focus:true,compose:true});core.qs('#lifestyleAI .alphaNewChatBtn')?.click()}
function closeFloating(){core.qsa('.olenChatSearch500,.olenChatActions500,.olenChatScrim500').forEach(el=>el.remove())}
function setOpen(on){const s=sidebar();document.body.classList.toggle(OPEN,!!on);document.body.classList.toggle('alphaChatOlenOpen4330',!!on);if(s){s.classList.toggle('show',!!on);s.setAttribute('aria-hidden',on?'false':'true');if(on)s.hidden=false}core.emit('chat:sidebar',{open:!!on})}
function openConversation(id){setOpen(false);for(const name of ['alphaOpenConversation','alphaLoadConversation','alphaSelectConversation']){if(typeof window[name]==='function'){core.safe(()=>window[name](id));return}}}
function messageText(c){return (c?.messages||[]).map(m=>String(m?.content||m?.text||'')).join(' ')}
function searchAll(query){const q=core.norm(query).toLocaleLowerCase('pt-PT');if(!q)return[];return activeConversations().filter(c=>(label(c)+' '+messageText(c)).toLocaleLowerCase('pt-PT').includes(q))}
function openSearch(){closeFloating();const wrap=document.createElement('section');wrap.className='olenChatSearch500';wrap.innerHTML=`<header><button aria-label="Voltar">${ICON.back}</button><input type="search" placeholder="Pesquisar conversas" autocomplete="off"></header><div class="olenChatResults500"></div>`;document.body.append(wrap);const input=wrap.querySelector('input'),results=wrap.querySelector('.olenChatResults500');wrap.querySelector('button').onclick=()=>wrap.remove();function render(){const hits=searchAll(input.value);results.replaceChildren();hits.forEach(c=>{const b=document.createElement('button');b.className='olenChatResult500';b.innerHTML=`<b>${core.escapeHTML(label(c))}</b><span>${core.escapeHTML(messageText(c).slice(0,220))}</span>`;b.onclick=()=>{wrap.remove();openConversation(c.id)};results.append(b)});if(input.value&&!hits.length)results.innerHTML='<div style="padding:28px;color:#93a9a2;text-align:center">Sem resultados.</div>'}input.addEventListener('input',render);setTimeout(()=>input.focus(),20)}
function togglePin(c){if(!c)return;const m=meta(),k=key(c),on=!m[k]?.pinned;m[k]={...(m[k]||{}),pinned:on};saveMeta(m);core.emit('chat:meta',{conversation:c,pinned:on})}
function archive(c){if(!c)return;const m=meta(),k=key(c);m[k]={...(m[k]||{}),archived:true};saveMeta(m);core.emit('chat:meta',{conversation:c,archived:true})}
function remove(c){if(!c||!confirm(`Eliminar "${label(c)}"?`))return;const m=meta(),k=key(c);m[k]={...(m[k]||{}),deleted:true};saveMeta(m);core.emit('chat:meta',{conversation:c,deleted:true})}
function openActions(anchor){closeFloating();const c=current();if(!c)return;const menu=document.createElement('div');menu.className='olenChatActions500';menu.innerHTML=`<button data-a="search">Pesquisar na conversa</button><button data-a="pin">${meta()[key(c)]?.pinned?'Desafixar':'Fixar'}</button><button data-a="archive">Arquivar</button><button class="danger" data-a="delete">Eliminar</button>`;document.body.append(menu);const r=anchor?.getBoundingClientRect?.();menu.style.right='14px';menu.style.top=Math.min(innerHeight-menu.offsetHeight-14,(r?.bottom||70)+8)+'px';menu.onclick=e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;menu.remove();if(a==='search')openCurrentSearch(c);if(a==='pin')togglePin(c);if(a==='archive')archive(c);if(a==='delete')remove(c)}}
function openCurrentSearch(c){const wrap=document.createElement('section');wrap.className='olenChatSearch500';wrap.innerHTML=`<header><button aria-label="Voltar">${ICON.back}</button><input type="search" placeholder="Pesquisar nesta conversa" autocomplete="off"></header><div class="olenChatResults500"></div>`;document.body.append(wrap);const input=wrap.querySelector('input'),out=wrap.querySelector('.olenChatResults500');wrap.querySelector('button').onclick=()=>wrap.remove();input.oninput=()=>{const q=core.norm(input.value).toLocaleLowerCase('pt-PT');out.replaceChildren();if(!q)return;(c.messages||[]).forEach(m=>{const t=String(m?.content||m?.text||'');if(!t.toLocaleLowerCase('pt-PT').includes(q))return;const card=document.createElement('div');card.className='olenChatResult500';card.innerHTML=`<span>${core.escapeHTML(t.slice(0,420))}</span>`;out.append(card)})};setTimeout(()=>input.focus(),20)}
function sync(){if(!core.isChat()){document.body.classList.remove(FS,OPEN);closeFloating();return}installStyle();ensureCapsule();const legacyOpen=document.body.classList.contains('alphaChatOlenOpen4330');document.body.classList.toggle(OPEN,legacyOpen)}
function init(){installStyle();core.listen(document,'click',e=>{const a=e.target.closest?.('[data-chat-action]');if(a?.dataset.chatAction==='new'){e.preventDefault();startFresh()}else if(a?.dataset.chatAction==='more'){e.preventDefault();openActions(a)}const search=e.target.closest?.('.alphaChatOlenSearch4330');if(search&&isOpen()){e.preventDefault();openSearch()}},true);core.listen(window,'pageshow',sync,{passive:true});core.listen(window,'popstate',sync,{passive:true});core.later(sync,80)}
window.OLEN.chat=Object.freeze({version:VERSION,init,sync,setOpen,openSearch,startFresh,searchAll});
})();
